- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME' )}}/.ssh/id_rsa"
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - core
        - extra
        - zsh
        - dotfiles
        - node
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/core.yml
    - include: tasks/zsh.yml
    - include: tasks/node.yml
    - include: tasks/dotfiles.yml

