- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME' )}}/.ssh/id_rsa"
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - ssh
        - core
        - zsh
        - tmux
        - node
        - dotfiles
  tasks:
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/core.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/node.yml
    - include_tasks: tasks/dotfiles.yml

