- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME' )}}/.ssh/id_rsa"
  pre_tasks:
    - name: Update apt
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - base
        - extra
  tasks:
  - name: Ensure ~/.ssh exists.
    file:
      dest: "{{ dest_key | dirname }}"
      mode: 0700
      state: directory
    tags:
      - base
      - extra
  - name: Install ssh_key
    copy:
      src: "{{ source_key }}"
      dest: "{{ dest_key }}"
      mode: 0600
    tags:
      - base
      - extra
  - name: Install ssh_key.pub
    copy:
      src: "{{ source_key }}.pub"
      dest: "{{ dest_key }}.pub"
      mode: 0644
    tags:
      - base
      - extra
  - name: Set authorized key
    authorized_key:
      user: "{{ lookup('env', 'USER') }}"
      state: present
      key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
    with_fileglob:
      - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
  - name: Install git & ZSH
    apt:
      name: ['git', 'zsh']
    tags:
      - base
      - exta
  - name: Change Shell
    shell: chsh -s `which zsh`
    tags:
      - base
      - extra
  - name: Install ohmyzsh [1/2]
    git:
      repo: https://github.com/robbyrussell/oh-my-zsh
      dest: ~/.oh-my-zsh
    tags:
      - base
      - extra
  - name: Install ohmyzsh [2/2]
    copy:
      src: ~/.oh-my-zsh/templates/zshrc.zsh-template
      dest: ~/.zshrc
  - name: Install Node.js & npm
    apt:
      name: ['nodejs', 'npm']
    tags:
      - base
      - extra
  - name: Install n
    npm:
      name: n
      global: true
    tags:
      - base
      - extra
  - name: Use Node.js LTS
    shell: n lts
    tags:
      - base
      - extra
  - name: Install diff-so-fancy
    npm:
      name: diff-so-fancy
      global: true
    tags:
      - base
      - extra
  - name: Install fzf
    apt: name=fzf
    tags:
      - base
      - extra
  - name: Install stow
    apt: name=stow
    tags:
      - base
      - extra
  - name: Clone .dotfiles
    git:
      repo: 'https://github.com/mbacalan/.dotfiles'
      dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
      recursive: yes
      update: yes
      accept_hostkey: yes
      version: master
    tags:
      - base
      - extra
  - name: Stow dotfiles
    shell: cd $HOME/.dotfiles && ./linux
    tags:
      - base
      - extra
